//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPO_lab_2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Database_v2Container : DbContext
    {
        public Database_v2Container()
            : base("name=Database_v2Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<planes> planesSet { get; set; }
        public virtual DbSet<airports> airportsSet { get; set; }
        public virtual DbSet<users> usersSet { get; set; }
        public virtual DbSet<flight> flightSet { get; set; }
        public virtual DbSet<tickets> ticketsSet { get; set; }
    }
}
