//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPO_lab_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class tickets
    {
        public int idTicket { get; set; }
        public string number { get; set; }
        public string seat { get; set; }
        public string price { get; set; }
    
        public virtual flight idFlight { get; set; }
        public virtual users idUser { get; set; }
    }
}
